version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=db_internal_transfers
    restart: unless-stopped

  prisma:
    image: prismagraphql/prisma:1.3.x
    build: backend/prisma
    restart: always
    depends_on:
      - postgres

    ports:
      - '4466:4466'
    environment:
      DATABASE_URL: postgresql://postgres:12345678@postgres:5432/db_internal_transfers
      PRISMA_CONFIG: |
        managementApiSecret: teste156
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: postgres
            password: 12345678
            connectionLimit: 2

  backend:
    links:
      - postgres
    depends_on:
      - postgres
      - prisma
    container_name: backend
    ports:
      - 3001:3001
    build: backend
    restart: on-failure
    environment:
      - DB_HOST=postgres
    volumes:
      - ./backend:/internal_transfers/backend
      - ./backend:/internal_transfers/backend/node_modules

  frontend:
    container_name: frontend
    build: frontend
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - backend
    volumes:
      - ./frontend:/internal_transfers/frontend
      - ./frontend:/internal_transfers/frontend/node_modules
